### ISSUE TITLE
System.Security.Cryptography.CryptographicException Error occured

### ISSUE THREAD

**Issue by yang-genmai** [CrowdStrike/falcon-orchestrator#54]
I was installed Falcon Orchestrator on Windows server 2016(AWS).
when I starting 'Falcon Orchestrator Client service', it goes stop. and log is 

`2018-10-03 11:06:46,481 DEBUG FalconOrchestrator.Client.FalconOrchestratorService - Connection to database is successful, starting service
2018-10-03 11:06:47,950 FATAL FalconOrchestrator.Client.FalconOrchestratorService - An unhandled error occured
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.RijndaelManagedTransform.DecryptData(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[]& outputBuffer, Int32 outputOffset, PaddingMode paddingMode, Boolean fLast)
   at System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at FalconOrchestrator.DAL.Crypto.AES_Decrypt(Byte[] bytesToBeDecrypted, Byte[] passwordBytes)
   at FalconOrchestrator.DAL.Crypto.DecryptText(String input, String password)
   at FalconOrchestrator.DAL.AppConfiguration.get_FALCON_STREAM_KEY()
   at FalconOrchestrator.Client.FalconOrchestratorService.Invoke()`

help me please.

**Comment by mr-burnse** [comment]
Sorry for the delayed response here. Please refer to issue #39 for more details. This usually occurs if the CryptoKey is changed.
