### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ineedasolution** [CrowdStrike/falcon-orchestrator#8]
Good morning,

We have encountered the following error this morning:

**Comment by ineedasolution** [comment]
2016-08-11 08:50:31,510 FATAL FalconOrchestrator.Client.FalconOrchestratorService - An unhandled error occured
System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at FalconOrchestrator.Client.FalconOrchestratorService.ProcessStream(Stream firehose)
   at FalconOrchestrator.Client.FalconOrchestratorService.Invoke()
2016-08-11 08:51:31,761 DEBUG FalconOrchestrator.Client.FalconOrchestratorService - Connection to database is successful, starting service
2016-08-11 08:51:33,511 FATAL FalconOrchestrator.Client.FalconOrchestratorService - An unhandled error occured
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.Create(String requestUriString)
   at FalconOrchestrator.Client.Connection.AuthenticateRequest()
   at FalconOrchestrator.Client.Connection.GetStream()
   at FalconOrchestrator.Client.FalconOrchestratorService.Invoke()

**Comment by ineedasolution** [comment]
We are unable to identify the issue?  Any thoughts?

**Comment by mr-burnse** [comment]
Have you modified the value of the URL under Config > Falcon Streaming API at all?  Also is this an intermittent error or persistent every time you restart the client service?

**Comment by mr-burnse** [comment]
Closing issue due to lack of response.  If you're still encountering this issue please comment and I'll re-open if necessary.
